const countries = [
  { code: "AF", en: "Afghanistan", zh: "阿富汗", flag: "https://flagcdn.com/w320/af.png" },
  { code: "AL", en: "Albania", zh: "阿尔巴尼亚", flag: "https://flagcdn.com/w320/al.png" },
  { code: "DZ", en: "Algeria", zh: "阿尔及利亚", flag: "https://flagcdn.com/w320/dz.png" },
  { code: "AD", en: "Andorra", zh: "安道尔", flag: "https://flagcdn.com/w320/ad.png" },
  { code: "AO", en: "Angola", zh: "安哥拉", flag: "https://flagcdn.com/w320/ao.png" },
  { code: "AG", en: "Antigua and Barbuda", zh: "安提瓜和巴布达", flag: "https://flagcdn.com/w320/ag.png" },
  { code: "AR", en: "Argentina", zh: "阿根廷", flag: "https://flagcdn.com/w320/ar.png" },
  { code: "AM", en: "Armenia", zh: "亚美尼亚", flag: "https://flagcdn.com/w320/am.png" },
  { code: "AW", en: "Aruba", zh: "阿鲁巴", flag: "https://flagcdn.com/w320/aw.png" },
  { code: "AU", en: "Australia", zh: "澳大利亚", flag: "https://flagcdn.com/w320/au.png" },
  { code: "AT", en: "Austria", zh: "奥地利", flag: "https://flagcdn.com/w320/at.png" },
  { code: "AZ", en: "Azerbaijan", zh: "阿塞拜疆", flag: "https://flagcdn.com/w320/az.png" },
  { code: "BS", en: "Bahamas", zh: "巴哈马", flag: "https://flagcdn.com/w320/bs.png" },
  { code: "BH", en: "Bahrain", zh: "巴林", flag: "https://flagcdn.com/w320/bh.png" },
  { code: "BD", en: "Bangladesh", zh: "孟加拉国", flag: "https://flagcdn.com/w320/bd.png" },
  { code: "BB", en: "Barbados", zh: "巴巴多斯", flag: "https://flagcdn.com/w320/bb.png" },
  { code: "BY", en: "Belarus", zh: "白俄罗斯", flag: "https://flagcdn.com/w320/by.png" },
  { code: "BE", en: "Belgium", zh: "比利时", flag: "https://flagcdn.com/w320/be.png" },
  { code: "BZ", en: "Belize", zh: "伯利兹", flag: "https://flagcdn.com/w320/bz.png" },
  { code: "BJ", en: "Benin", zh: "贝宁", flag: "https://flagcdn.com/w320/bj.png" },
  { code: "BM", en: "Bermuda", zh: "百慕大", flag: "https://flagcdn.com/w320/bm.png" },
  { code: "BT", en: "Bhutan", zh: "不丹", flag: "https://flagcdn.com/w320/bt.png" },
  { code: "BO", en: "Bolivia", zh: "玻利维亚", flag: "https://flagcdn.com/w320/bo.png" },
  { code: "BQ", en: "Caribbean Netherlands", zh: "荷属加勒比区", flag: "https://flagcdn.com/w320/bq.png" },
  { code: "BA", en: "Bosnia and Herzegovina", zh: "波斯尼亚和黑塞哥维那", flag: "https://flagcdn.com/w320/ba.png" },
  { code: "BW", en: "Botswana", zh: "博茨瓦纳", flag: "https://flagcdn.com/w320/bw.png" },
  { code: "BV", en: "Bouvet Island", zh: "布韦岛", flag: "https://flagcdn.com/w320/bv.png" },
  { code: "BR", en: "Brazil", zh: "巴西", flag: "https://flagcdn.com/w320/br.png" },
  { code: "IO", en: "British Indian Ocean Territory", zh: "英属印度洋领地", flag: "https://flagcdn.com/w320/io.png" },
  { code: "BN", en: "Brunei", zh: "文莱", flag: "https://flagcdn.com/w320/bn.png" },
  { code: "BG", en: "Bulgaria", zh: "保加利亚", flag: "https://flagcdn.com/w320/bg.png" },
  { code: "BF", en: "Burkina Faso", zh: "布基纳法索", flag: "https://flagcdn.com/w320/bf.png" },
  { code: "BI", en: "Burundi", zh: "布隆迪", flag: "https://flagcdn.com/w320/bi.png" },
  { code: "KH", en: "Cambodia", zh: "柬埔寨", flag: "https://flagcdn.com/w320/kh.png" },
  { code: "CM", en: "Cameroon", zh: "喀麦隆", flag: "https://flagcdn.com/w320/cm.png" },
  { code: "CA", en: "Canada", zh: "加拿大", flag: "https://flagcdn.com/w320/ca.png" },
  { code: "CV", en: "Cape Verde", zh: "佛得角", flag: "https://flagcdn.com/w320/cv.png" },
  { code: "KY", en: "Cayman Islands", zh: "开曼群岛", flag: "https://flagcdn.com/w320/ky.png" },
  { code: "CF", en: "Central African Republic", zh: "中非共和国", flag: "https://flagcdn.com/w320/cf.png" },
  { code: "TD", en: "Chad", zh: "乍得", flag: "https://flagcdn.com/w320/td.png" },
  { code: "CL", en: "Chile", zh: "智利", flag: "https://flagcdn.com/w320/cl.png" },
  { code: "CN", en: "China", zh: "中国", flag: "https://flagcdn.com/w320/cn.png" },
  { code: "HK", en: "Hong Kong", zh: "中国香港", flag: "https://flagcdn.com/w320/hk.png" },
  { code: "MO", en: "Macao", zh: "中国澳门", flag: "https://flagcdn.com/w320/mo.png" },
  { code: "CX", en: "Christmas Island", zh: "圣诞岛", flag: "https://flagcdn.com/w320/cx.png" },
  { code: "CC", en: "Cocos (Keeling) Islands", zh: "科科斯（基林）群岛", flag: "https://flagcdn.com/w320/cc.png" },
  { code: "CO", en: "Colombia", zh: "哥伦比亚", flag: "https://flagcdn.com/w320/co.png" },
  { code: "KM", en: "Comoros", zh: "科摩罗", flag: "https://flagcdn.com/w320/km.png" },
  { code: "CG", en: "Congo", zh: "刚果（布）", flag: "https://flagcdn.com/w320/cg.png" },
  { code: "CD", en: "Congo (DRC)", zh: "刚果（金）", flag: "https://flagcdn.com/w320/cd.png" },
  { code: "CK", en: "Cook Islands", zh: "库克群岛", flag: "https://flagcdn.com/w320/ck.png" },
  { code: "CR", en: "Costa Rica", zh: "哥斯达黎加", flag: "https://flagcdn.com/w320/cr.png" },
  { code: "HR", en: "Croatia", zh: "克罗地亚", flag: "https://flagcdn.com/w320/hr.png" },
  { code: "CU", en: "Cuba", zh: "古巴", flag: "https://flagcdn.com/w320/cu.png" },
  { code: "CW", en: "Curaçao", zh: "库拉索", flag: "https://flagcdn.com/w320/cw.png" },
  { code: "CY", en: "Cyprus", zh: "塞浦路斯", flag: "https://flagcdn.com/w320/cy.png" },
  { code: "CZ", en: "Czechia", zh: "捷克", flag: "https://flagcdn.com/w320/cz.png" },
  { code: "DK", en: "Denmark", zh: "丹麦", flag: "https://flagcdn.com/w320/dk.png" },
  { code: "DJ", en: "Djibouti", zh: "吉布提", flag: "https://flagcdn.com/w320/dj.png" },
  { code: "DM", en: "Dominica", zh: "多米尼克", flag: "https://flagcdn.com/w320/dm.png" },
  { code: "DO", en: "Dominican Republic", zh: "多米尼加共和国", flag: "https://flagcdn.com/w320/do.png" },
  { code: "EC", en: "Ecuador", zh: "厄瓜多尔", flag: "https://flagcdn.com/w320/ec.png" },
  { code: "EG", en: "Egypt", zh: "埃及", flag: "https://flagcdn.com/w320/eg.png" },
  { code: "SV", en: "El Salvador", zh: "萨尔瓦多", flag: "https://flagcdn.com/w320/sv.png" },
  { code: "GQ", en: "Equatorial Guinea", zh: "赤道几内亚", flag: "https://flagcdn.com/w320/gq.png" },
  { code: "ER", en: "Eritrea", zh: "厄立特里亚", flag: "https://flagcdn.com/w320/er.png" },
  { code: "EE", en: "Estonia", zh: "爱沙尼亚", flag: "https://flagcdn.com/w320/ee.png" },
  { code: "SZ", en: "Eswatini", zh: "斯威士兰", flag: "https://flagcdn.com/w320/sz.png" },
  { code: "ET", en: "Ethiopia", zh: "埃塞俄比亚", flag: "https://flagcdn.com/w320/et.png" },
  { code: "FK", en: "Falkland Islands", zh: "福克兰群岛", flag: "https://flagcdn.com/w320/fk.png" },
  { code: "FO", en: "Faroe Islands", zh: "法罗群岛", flag: "https://flagcdn.com/w320/fo.png" },
  { code: "FJ", en: "Fiji", zh: "斐济", flag: "https://flagcdn.com/w320/fj.png" },
  { code: "FI", en: "Finland", zh: "芬兰", flag: "https://flagcdn.com/w320/fi.png" },
  { code: "FR", en: "France", zh: "法国", flag: "https://flagcdn.com/w320/fr.png" },
  { code: "GF", en: "French Guiana", zh: "法属圭亚那", flag: "https://flagcdn.com/w320/gf.png" },
  { code: "PF", en: "French Polynesia", zh: "法属波利尼西亚", flag: "https://flagcdn.com/w320/pf.png" },
  { code: "TF", en: "French Southern Territories", zh: "法属南部领地", flag: "https://flagcdn.com/w320/tf.png" },
  { code: "GA", en: "Gabon", zh: "加蓬", flag: "https://flagcdn.com/w320/ga.png" },
  { code: "GM", en: "Gambia", zh: "冈比亚", flag: "https://flagcdn.com/w320/gm.png" },
  { code: "GE", en: "Georgia", zh: "格鲁吉亚", flag: "https://flagcdn.com/w320/ge.png" },
  { code: "DE", en: "Germany", zh: "德国", flag: "https://flagcdn.com/w320/de.png" },
  { code: "GH", en: "Ghana", zh: "加纳", flag: "https://flagcdn.com/w320/gh.png" },
  { code: "GI", en: "Gibraltar", zh: "直布罗陀", flag: "https://flagcdn.com/w320/gi.png" },
  { code: "GR", en: "Greece", zh: "希腊", flag: "https://flagcdn.com/w320/gr.png" },
  { code: "GL", en: "Greenland", zh: "格陵兰", flag: "https://flagcdn.com/w320/gl.png" },
  { code: "GD", en: "Grenada", zh: "格林纳达", flag: "https://flagcdn.com/w320/gd.png" },
  { code: "GP", en: "Guadeloupe", zh: "瓜德罗普", flag: "https://flagcdn.com/w320/gp.png" },
  { code: "GU", en: "Guam", zh: "关岛", flag: "https://flagcdn.com/w320/gu.png" },
  { code: "GT", en: "Guatemala", zh: "危地马拉", flag: "https://flagcdn.com/w320/gt.png" },
  { code: "GG", en: "Guernsey", zh: "根西岛", flag: "https://flagcdn.com/w320/gg.png" },
  { code: "GN", en: "Guinea", zh: "几内亚", flag: "https://flagcdn.com/w320/gn.png" },
  { code: "GW", en: "Guinea-Bissau", zh: "几内亚比绍", flag: "https://flagcdn.com/w320/gw.png" },
  { code: "GY", en: "Guyana", zh: "圭亚那", flag: "https://flagcdn.com/w320/gy.png" },
  { code: "HT", en: "Haiti", zh: "海地", flag: "https://flagcdn.com/w320/ht.png" },
  { code: "HM", en: "Heard Island and McDonald Islands", zh: "赫德岛和麦克唐纳群岛", flag: "https://flagcdn.com/w320/hm.png" },
  { code: "VA", en: "Vatican City", zh: "梵蒂冈", flag: "https://flagcdn.com/w320/va.png" },
  { code: "HN", en: "Honduras", zh: "洪都拉斯", flag: "https://flagcdn.com/w320/hn.png" },
  { code: "HU", en: "Hungary", zh: "匈牙利", flag: "https://flagcdn.com/w320/hu.png" },
  { code: "IS", en: "Iceland", zh: "冰岛", flag: "https://flagcdn.com/w320/is.png" },
  { code: "IN", en: "India", zh: "印度", flag: "https://flagcdn.com/w320/in.png" },
  { code: "ID", en: "Indonesia", zh: "印度尼西亚", flag: "https://flagcdn.com/w320/id.png" },
  { code: "IR", en: "Iran", zh: "伊朗", flag: "https://flagcdn.com/w320/ir.png" },
  { code: "IQ", en: "Iraq", zh: "伊拉克", flag: "https://flagcdn.com/w320/iq.png" },
  { code: "IE", en: "Ireland", zh: "爱尔兰", flag: "https://flagcdn.com/w320/ie.png" },
  { code: "IM", en: "Isle of Man", zh: "马恩岛", flag: "https://flagcdn.com/w320/im.png" },
  { code: "IL", en: "Israel", zh: "以色列", flag: "https://flagcdn.com/w320/il.png" },
  { code: "IT", en: "Italy", zh: "意大利", flag: "https://flagcdn.com/w320/it.png" },
  { code: "JM", en: "Jamaica", zh: "牙买加", flag: "https://flagcdn.com/w320/jm.png" },
  { code: "JP", en: "Japan", zh: "日本", flag: "https://flagcdn.com/w320/jp.png" },
  { code: "JE", en: "Jersey", zh: "泽西岛", flag: "https://flagcdn.com/w320/je.png" },
  { code: "JO", en: "Jordan", zh: "约旦", flag: "https://flagcdn.com/w320/jo.png" },
  { code: "KZ", en: "Kazakhstan", zh: "哈萨克斯坦", flag: "https://flagcdn.com/w320/kz.png" },
  { code: "KE", en: "Kenya", zh: "肯尼亚", flag: "https://flagcdn.com/w320/ke.png" },
  { code: "KI", en: "Kiribati", zh: "基里巴斯", flag: "https://flagcdn.com/w320/ki.png" },
  { code: "XK", en: "Kosovo", zh: "科索沃", flag: "https://flagcdn.com/w320/xk.png" },
  { code: "KW", en: "Kuwait", zh: "科威特", flag: "https://flagcdn.com/w320/kw.png" },
  { code: "KG", en: "Kyrgyzstan", zh: "吉尔吉斯斯坦", flag: "https://flagcdn.com/w320/kg.png" },
  { code: "LA", en: "Laos", zh: "老挝", flag: "https://flagcdn.com/w320/la.png" },
  { code: "LV", en: "Latvia", zh: "拉脱维亚", flag: "https://flagcdn.com/w320/lv.png" },
  { code: "LB", en: "Lebanon", zh: "黎巴嫩", flag: "https://flagcdn.com/w320/lb.png" },
  { code: "LS", en: "Lesotho", zh: "莱索托", flag: "https://flagcdn.com/w320/ls.png" },
  { code: "LR", en: "Liberia", zh: "利比里亚", flag: "https://flagcdn.com/w320/lr.png" },
  { code: "LY", en: "Libya", zh: "利比亚", flag: "https://flagcdn.com/w320/ly.png" },
  { code: "LI", en: "Liechtenstein", zh: "列支敦士登", flag: "https://flagcdn.com/w320/li.png" },
  { code: "LT", en: "Lithuania", zh: "立陶宛", flag: "https://flagcdn.com/w320/lt.png" },
  { code: "LU", en: "Luxembourg", zh: "卢森堡", flag: "https://flagcdn.com/w320/lu.png" },
  { code: "MG", en: "Madagascar", zh: "马达加斯加", flag: "https://flagcdn.com/w320/mg.png" },
  { code: "MW", en: "Malawi", zh: "马拉维", flag: "https://flagcdn.com/w320/mw.png" },
  { code: "MY", en: "Malaysia", zh: "马来西亚", flag: "https://flagcdn.com/w320/my.png" },
  { code: "MV", en: "Maldives", zh: "马尔代夫", flag: "https://flagcdn.com/w320/mv.png" },
  { code: "ML", en: "Mali", zh: "马里", flag: "https://flagcdn.com/w320/ml.png" },
  { code: "MT", en: "Malta", zh: "马耳他", flag: "https://flagcdn.com/w320/mt.png" },
  { code: "MH", en: "Marshall Islands", zh: "马绍尔群岛", flag: "https://flagcdn.com/w320/mh.png" },
  { code: "MQ", en: "Martinique", zh: "马提尼克", flag: "https://flagcdn.com/w320/mq.png" },
  { code: "MR", en: "Mauritania", zh: "毛里塔尼亚", flag: "https://flagcdn.com/w320/mr.png" },
  { code: "MU", en: "Mauritius", zh: "毛里求斯", flag: "https://flagcdn.com/w320/mu.png" },
  { code: "YT", en: "Mayotte", zh: "马约特", flag: "https://flagcdn.com/w320/yt.png" },
  { code: "MX", en: "Mexico", zh: "墨西哥", flag: "https://flagcdn.com/w320/mx.png" },
  { code: "FM", en: "Micronesia", zh: "密克罗尼西亚", flag: "https://flagcdn.com/w320/fm.png" },
  { code: "MD", en: "Moldova", zh: "摩尔多瓦", flag: "https://flagcdn.com/w320/md.png" },
  { code: "MC", en: "Monaco", zh: "摩纳哥", flag: "https://flagcdn.com/w320/mc.png" },
  { code: "MN", en: "Mongolia", zh: "蒙古", flag: "https://flagcdn.com/w320/mn.png" },
  { code: "ME", en: "Montenegro", zh: "黑山", flag: "https://flagcdn.com/w320/me.png" },
  { code: "MS", en: "Montserrat", zh: "蒙特塞拉特", flag: "https://flagcdn.com/w320/ms.png" },
  { code: "MA", en: "Morocco", zh: "摩洛哥", flag: "https://flagcdn.com/w320/ma.png" },
  { code: "MZ", en: "Mozambique", zh: "莫桑比克", flag: "https://flagcdn.com/w320/mz.png" },
  { code: "MM", en: "Myanmar", zh: "缅甸", flag: "https://flagcdn.com/w320/mm.png" },
  { code: "NA", en: "Namibia", zh: "纳米比亚", flag: "https://flagcdn.com/w320/na.png" },
  { code: "NR", en: "Nauru", zh: "瑙鲁", flag: "https://flagcdn.com/w320/nr.png" },
  { code: "NP", en: "Nepal", zh: "尼泊尔", flag: "https://flagcdn.com/w320/np.png" },
  { code: "NL", en: "Netherlands", zh: "荷兰", flag: "https://flagcdn.com/w320/nl.png" },
  { code: "NC", en: "New Caledonia", zh: "新喀里多尼亚", flag: "https://flagcdn.com/w320/nc.png" },
  { code: "NZ", en: "New Zealand", zh: "新西兰", flag: "https://flagcdn.com/w320/nz.png" },
  { code: "NI", en: "Nicaragua", zh: "尼加拉瓜", flag: "https://flagcdn.com/w320/ni.png" },
  { code: "NE", en: "Niger", zh: "尼日尔", flag: "https://flagcdn.com/w320/ne.png" },
  { code: "NG", en: "Nigeria", zh: "尼日利亚", flag: "https://flagcdn.com/w320/ng.png" },
  { code: "NU", en: "Niue", zh: "纽埃", flag: "https://flagcdn.com/w320/nu.png" },
  { code: "NF", en: "Norfolk Island", zh: "诺福克岛", flag: "https://flagcdn.com/w320/nf.png" },
  { code: "MK", en: "North Macedonia", zh: "北马其顿", flag: "https://flagcdn.com/w320/mk.png" },
  { code: "MP", en: "Northern Mariana Islands", zh: "北马里亚纳群岛", flag: "https://flagcdn.com/w320/mp.png" },
  { code: "NO", en: "Norway", zh: "挪威", flag: "https://flagcdn.com/w320/no.png" },
  { code: "OM", en: "Oman", zh: "阿曼", flag: "https://flagcdn.com/w320/om.png" },
  { code: "PK", en: "Pakistan", zh: "巴基斯坦", flag: "https://flagcdn.com/w320/pk.png" },
  { code: "PW", en: "Palau", zh: "帕劳", flag: "https://flagcdn.com/w320/pw.png" },
  { code: "PS", en: "Palestine", zh: "巴勒斯坦", flag: "https://flagcdn.com/w320/ps.png" },
  { code: "PA", en: "Panama", zh: "巴拿马", flag: "https://flagcdn.com/w320/pa.png" },
  { code: "PG", en: "Papua New Guinea", zh: "巴布亚新几内亚", flag: "https://flagcdn.com/w320/pg.png" },
  { code: "PY", en: "Paraguay", zh: "巴拉圭", flag: "https://flagcdn.com/w320/py.png" },
  { code: "PE", en: "Peru", zh: "秘鲁", flag: "https://flagcdn.com/w320/pe.png" },
  { code: "PH", en: "Philippines", zh: "菲律宾", flag: "https://flagcdn.com/w320/ph.png" },
  { code: "PN", en: "Pitcairn Islands", zh: "皮特凯恩群岛", flag: "https://flagcdn.com/w320/pn.png" },
  { code: "PL", en: "Poland", zh: "波兰", flag: "https://flagcdn.com/w320/pl.png" },
  { code: "PT", en: "Portugal", zh: "葡萄牙", flag: "https://flagcdn.com/w320/pt.png" },
  { code: "PR", en: "Puerto Rico", zh: "波多黎各", flag: "https://flagcdn.com/w320/pr.png" },
  { code: "QA", en: "Qatar", zh: "卡塔尔", flag: "https://flagcdn.com/w320/qa.png" },
  { code: "RE", en: "Réunion", zh: "留尼汪", flag: "https://flagcdn.com/w320/re.png" },
  { code: "RO", en: "Romania", zh: "罗马尼亚", flag: "https://flagcdn.com/w320/ro.png" },
  { code: "RU", en: "Russia", zh: "俄罗斯", flag: "https://flagcdn.com/w320/ru.png" },
  { code: "RW", en: "Rwanda", zh: "卢旺达", flag: "https://flagcdn.com/w320/rw.png" },
  { code: "BL", en: "Saint Barthélemy", zh: "圣巴泰勒米", flag: "https://flagcdn.com/w320/bl.png" },
  { code: "SH", en: "Saint Helena", zh: "圣赫勒拿", flag: "https://flagcdn.com/w320/sh.png" },
  { code: "KN", en: "Saint Kitts and Nevis", zh: "圣基茨和尼维斯", flag: "https://flagcdn.com/w320/kn.png" },
  { code: "LC", en: "Saint Lucia", zh: "圣卢西亚", flag: "https://flagcdn.com/w320/lc.png" },
  { code: "MF", en: "Saint Martin", zh: "法属圣马丁", flag: "https://flagcdn.com/w320/mf.png" },
  { code: "PM", en: "Saint Pierre and Miquelon", zh: "圣皮埃尔和密克隆", flag: "https://flagcdn.com/w320/pm.png" },
  { code: "VC", en: "Saint Vincent and the Grenadines", zh: "圣文森特和格林纳丁斯", flag: "https://flagcdn.com/w320/vc.png" },
  { code: "WS", en: "Samoa", zh: "萨摩亚", flag: "https://flagcdn.com/w320/ws.png" },
  { code: "SM", en: "San Marino", zh: "圣马力诺", flag: "https://flagcdn.com/w320/sm.png" },
  { code: "ST", en: "Sao Tome and Principe", zh: "圣多美和普林西比", flag: "https://flagcdn.com/w320/st.png" },
  { code: "SA", en: "Saudi Arabia", zh: "沙特阿拉伯", flag: "https://flagcdn.com/w320/sa.png" },
  { code: "SN", en: "Senegal", zh: "塞内加尔", flag: "https://flagcdn.com/w320/sn.png" },
  { code: "RS", en: "Serbia", zh: "塞尔维亚", flag: "https://flagcdn.com/w320/rs.png" },
  { code: "SC", en: "Seychelles", zh: "塞舌尔", flag: "https://flagcdn.com/w320/sc.png" },
  { code: "SL", en: "Sierra Leone", zh: "塞拉利昂", flag: "https://flagcdn.com/w320/sl.png" },
  { code: "SG", en: "Singapore", zh: "新加坡", flag: "https://flagcdn.com/w320/sg.png" },
  { code: "SX", en: "Sint Maarten", zh: "荷属圣马丁", flag: "https://flagcdn.com/w320/sx.png" },
  { code: "SK", en: "Slovakia", zh: "斯洛伐克", flag: "https://flagcdn.com/w320/sk.png" },
  { code: "SI", en: "Slovenia", zh: "斯洛文尼亚", flag: "https://flagcdn.com/w320/si.png" },
  { code: "SB", en: "Solomon Islands", zh: "所罗门群岛", flag: "https://flagcdn.com/w320/sb.png" },
  { code: "SO", en: "Somalia", zh: "索马里", flag: "https://flagcdn.com/w320/so.png" },
  { code: "ZA", en: "South Africa", zh: "南非", flag: "https://flagcdn.com/w320/za.png" },
  { code: "GS", en: "South Georgia and the South Sandwich Islands", zh: "南乔治亚和南桑威奇群岛", flag: "https://flagcdn.com/w320/gs.png" },
  { code: "KR", en: "South Korea", zh: "韩国", flag: "https://flagcdn.com/w320/kr.png" },
  { code: "SS", en: "South Sudan", zh: "南苏丹", flag: "https://flagcdn.com/w320/ss.png" },
  { code: "ES", en: "Spain", zh: "西班牙", flag: "https://flagcdn.com/w320/es.png" },
  { code: "LK", en: "Sri Lanka", zh: "斯里兰卡", flag: "https://flagcdn.com/w320/lk.png" },
  { code: "SD", en: "Sudan", zh: "苏丹", flag: "https://flagcdn.com/w320/sd.png" },
  { code: "SR", en: "Suriname", zh: "苏里南", flag: "https://flagcdn.com/w320/sr.png" },
  { code: "SJ", en: "Svalbard and Jan Mayen", zh: "斯瓦尔巴和扬马延", flag: "https://flagcdn.com/w320/sj.png" },
  { code: "SE", en: "Sweden", zh: "瑞典", flag: "https://flagcdn.com/w320/se.png" },
  { code: "CH", en: "Switzerland", zh: "瑞士", flag: "https://flagcdn.com/w320/ch.png" },
  { code: "SY", en: "Syria", zh: "叙利亚", flag: "https://flagcdn.com/w320/sy.png" },
  { code: "TJ", en: "Tajikistan", zh: "塔吉克斯坦", flag: "https://flagcdn.com/w320/tj.png" },
  { code: "TZ", en: "Tanzania", zh: "坦桑尼亚", flag: "https://flagcdn.com/w320/tz.png" },
  { code: "TH", en: "Thailand", zh: "泰国", flag: "https://flagcdn.com/w320/th.png" },
  { code: "TL", en: "Timor-Leste", zh: "东帝汶", flag: "https://flagcdn.com/w320/tl.png" },
  { code: "TG", en: "Togo", zh: "多哥", flag: "https://flagcdn.com/w320/tg.png" },
  { code: "TK", en: "Tokelau", zh: "托克劳", flag: "https://flagcdn.com/w320/tk.png" },
  { code: "TO", en: "Tonga", zh: "汤加", flag: "https://flagcdn.com/w320/to.png" },
  { code: "TT", en: "Trinidad and Tobago", zh: "特立尼达和多巴哥", flag: "https://flagcdn.com/w320/tt.png" },
  { code: "TN", en: "Tunisia", zh: "突尼斯", flag: "https://flagcdn.com/w320/tn.png" },
  { code: "TR", en: "Turkey", zh: "土耳其", flag: "https://flagcdn.com/w320/tr.png" },
  { code: "TM", en: "Turkmenistan", zh: "土库曼斯坦", flag: "https://flagcdn.com/w320/tm.png" },
  { code: "TC", en: "Turks and Caicos Islands", zh: "特克斯和凯科斯群岛", flag: "https://flagcdn.com/w320/tc.png" },
  { code: "TV", en: "Tuvalu", zh: "图瓦卢", flag: "https://flagcdn.com/w320/tv.png" },
  { code: "UG", en: "Uganda", zh: "乌干达", flag: "https://flagcdn.com/w320/ug.png" },
  { code: "UA", en: "Ukraine", zh: "乌克兰", flag: "https://flagcdn.com/w320/ua.png" },
  { code: "AE", en: "United Arab Emirates", zh: "阿联酋", flag: "https://flagcdn.com/w320/ae.png" },
  { code: "GB", en: "United Kingdom", zh: "英国", flag: "https://flagcdn.com/w320/gb.png" },
  { code: "UM", en: "United States Minor Outlying Islands", zh: "美国本土外小岛屿", flag: "https://flagcdn.com/w320/um.png" },
  { code: "US", en: "United States", zh: "美国", flag: "https://flagcdn.com/w320/us.png" },
  { code: "UY", en: "Uruguay", zh: "乌拉圭", flag: "https://flagcdn.com/w320/uy.png" },
  { code: "UZ", en: "Uzbekistan", zh: "乌兹别克斯坦", flag: "https://flagcdn.com/w320/uz.png" },
  { code: "VU", en: "Vanuatu", zh: "瓦努阿图", flag: "https://flagcdn.com/w320/vu.png" },
  { code: "VA", en: "Vatican City", zh: "梵蒂冈", flag: "https://flagcdn.com/w320/va.png" },
  { code: "VE", en: "Venezuela", zh: "委内瑞拉", flag: "https://flagcdn.com/w320/ve.png" },
  { code: "VN", en: "Vietnam", zh: "越南", flag: "https://flagcdn.com/w320/vn.png" },
  { code: "VG", en: "British Virgin Islands", zh: "英属维尔京群岛", flag: "https://flagcdn.com/w320/vg.png" },
  { code: "VI", en: "U.S. Virgin Islands", zh: "美属维尔京群岛", flag: "https://flagcdn.com/w320/vi.png" },
  { code: "WF", en: "Wallis and Futuna", zh: "瓦利斯和富图纳", flag: "https://flagcdn.com/w320/wf.png" },
  { code: "EH", en: "Western Sahara", zh: "西撒哈拉", flag: "https://flagcdn.com/w320/eh.png" },
  { code: "YE", en: "Yemen", zh: "也门", flag: "https://flagcdn.com/w320/ye.png" },
  { code: "ZM", en: "Zambia", zh: "赞比亚", flag: "https://flagcdn.com/w320/zm.png" },
  { code: "ZW", en: "Zimbabwe", zh: "津巴布韦", flag: "https://flagcdn.com/w320/zw.png" }
];